### ISSUE TITLE
Add support for anonymous functions (eval)

### ISSUE THREAD

**Issue by genielabs** [stacktracejs/stackframe#12]
Given an error stack like this one:

```
ReferenceError: a is not defined
    at $$.onStart (eval at <anonymous> (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6851:25), <anonymous>:32:7)
    at $$.RenderWidget (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6770:36)
    at $$.RenderView (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6757:12)
    at http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6879:24
    at Object.$.ajax.success (http://localhost:8080/hg/html/js/homegenie.api.js?version=r525:724:21)
    at l (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:3:24881)
    at Object.c.fireWith [as resolveWith] (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:3:25702)
    at k (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:5:4919)
    at XMLHttpRequest.<anonymous> (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:5:8723)
```

stackframe will currently ignore the eval `<anonymous>:32:7` at the end of the first stack element, which is the real source of the error at line 32, column 7.
It will indeed report **stack[0]** with line **6851** and column **25**.

**Comment by eriwen** [comment]
@genielabs Stackframe itself handles `eval` origins as you can `setEvalOrigin(Stackframe)`. However, `error-stack-parser` does not set eval origins yet, so I'm going to move this issue to that project. Thanks for submitting.

**Comment by eriwen** [comment]
Issue moved to [stacktracejs/error-stack-parser #32](https://github.com/stacktracejs/error-stack-parser/issues/32) via [**ZenHub**](https://www.zenhub.com/)
