### ISSUE TITLE
No matching version found for stackframe@1.3.0

### ISSUE THREAD

**Issue by w611363303798** [stacktracejs/stackframe#47]

**Comment by dontdrinkmylemontea** [comment]
Is there any solutions? 🙁

**Comment by MoonCheung** [comment]
I have encountered it, but when packaged, `dist` also reported an error: `TypeError: StackFrame is not a constructor`
```javascript
 ERROR  TypeError: StackFrame is not a constructor
TypeError: StackFrame is not a constructor
    at Object.<anonymous> (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/error-stack-parser/error-stack-parser.js:76:24)
    at Array.map (<anonymous>)
    at Object.ErrorStackParser$$parseV8OrIE [as parseV8OrIE] (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/error-stack-parser/error-stack-parser.js:56:29)
    at Object.ErrorStackParser$$parse [as parse] (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/error-stack-parser/error-stack-parser.js:31:29)
    at getOriginalErrorStack (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/mooncheung/Documents/mooncheung/weiwang_project/vue-admin-element/node_modules/webpack/lib/Compiler.js:485:14
```

**Comment by Shark126** [comment]
Is there any solutions?

**Comment by dontdrinkmylemontea** [comment]
can see 1.3.0 versions in npmjs, but can't download

https://www.npmjs.com/package/stackframe

**Comment by ZhengXiaowei** [comment]
the same issue

**Comment by doooooit** [comment]
same issue

**Comment by manydots** [comment]
same issue

**Comment by kongta** [comment]
same issue

**Comment by Necroogre** [comment]
same issue

**Comment by HelloAndyZhang** [comment]
same issue

**Comment by LiuJinYang9527** [comment]
same issue

**Comment by SevenKismet** [comment]
same issue

**Comment by xlanghejianfeng** [comment]
same issue

**Comment by lltx** [comment]
```
npm install --package-lock-only


vim package-lock.json

# find "stackframe": "v1.3.0" replace 1.3.2
```

**Comment by gj19910723** [comment]
same issue

**Comment by zouyn** [comment]
same issue

**Comment by fuzi1996** [comment]
This is not a bug.I guess you all use private sources. Don't do anything. Just wait a minute (maybe a few minutes, maybe a few hours)

**Comment by jonny-wei** [comment]
TypeError: StackFrame is not a constructor

**Comment by gj19910723** [comment]
I used nexus  proxy  to mirror npm site. I changed  proxy to https://registry.npmjs.org and clean cache then i can download it.
but still have exception: ERROR  TypeError: StackFrame is not a constructor

**Comment by ZhengXiaowei** [comment]
> This is not a bug.I guess you all use private proxy registry. Don't do anything. Just wait a minute (maybe a few minutes, maybe a few hours)

yeah, i try it again, it's ok now

**Comment by Jazzzhang** [comment]
> > 这不是错误。我猜你们都使用私有代理注册表。不要做任何事。等一下（也许几分钟，也许几个小时）
> 
> 是的，我再试一次，现在好了



> same issue

**Comment by eriwen** [comment]
This is likely a CDN issue. Please use v1.3.4 if you encounter `StackFrame is not a constructor`
