### ISSUE TITLE
TypeError: StackFrame is not a constructor

### ISSUE THREAD

**Issue by sixgodIT** [stacktracejs/stackframe#51]
ERROR  TypeError: StackFrame is not a constructor
TypeError: StackFrame is not a constructor
    at Object.<anonymous> (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/error-stack-parser/error-stack-parser.js:76:24)
    at Array.map (<anonymous>)
    at Object.ErrorStackParser$$parseV8OrIE [as parseV8OrIE] (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/error-stack-parser/error-stack-parser.js:56:29)
    at Object.ErrorStackParser$$parse [as parse] (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/error-stack-parser/error-stack-parser.js:31:29)
    at getOriginalErrorStack (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/home/work/jenkins/workspace/FX-BE_fenxi-analysis-front/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)

**Comment by tcstory** [comment]
met the same problem

**Comment by hoowhoami** [comment]
met the same problem

**Comment by yj1438** [comment]
+1

**Comment by zksfyz** [comment]
+1

**Comment by hustlz** [comment]
+1

**Comment by paozi528** [comment]
+1

**Comment by BenHsiung** [comment]
+1

**Comment by eriwen** [comment]
I've released stackframe v1.3.4 to address this issue. Please update and add a comment here if it doesn't work for you.

**Comment by sixgodIT** [comment]
> I've released stackframe v1.3.4 to address this issue. Please update and add a comment here if it doesn't work for you.

OK，3Q

**Comment by BenHsiung** [comment]
1.3.4 works for me
